# Generated by Django 4.2.24 on 2025-09-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_updated_on_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
